version: "3"
services:
  mongoDb:
    image: mongo:7.0.23
    restart: always
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - "./Data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongoDb