name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Needed so the action can POST dependency snapshots
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build product-service
        run: mvn -B -ntp -f product-service/pom.xml package

      # Only submit dependencies when the token has write perms (push to main)
      - name: Submit dependency snapshot
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: advanced-security/maven-dependency-submission-action@v5
        with:
          directory: product-service
